version: "3"

services:
  node-server:
    image: tpblock/fibos-node:v5.0.3.0
    volumes:
      - ./fibos-node/data:/node/data
    ports:
      - "8080:8870"
      - "9870:9870"
    env_file:
      - ./.env
    entrypoint: [ "sh", "-c", "curl -O https://gist.githubusercontent.com/mingfunwong/d3f655ae7db52381a242fbf33226711f/raw/0463d46c4be8120dc6be7ce6f41cd99e3cb0bd98/fibos-start-snapshot.sh && bash fibos-start-snapshot.sh" ]
    restart: unless-stopped
